// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPukuTdNmQQbkQwy1w9XR4n-UA7Y6irGU',
    appId: '1:200767412375:web:ce7fe4c8a156d6450af1d2',
    messagingSenderId: '200767412375',
    projectId: 'smd-project-95ed9',
    authDomain: 'smd-project-95ed9.firebaseapp.com',
    storageBucket: 'smd-project-95ed9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHgSixK3kok6Ybw-hkyOih55CNFZSOQpM',
    appId: '1:200767412375:android:142a6f62df0579940af1d2',
    messagingSenderId: '200767412375',
    projectId: 'smd-project-95ed9',
    storageBucket: 'smd-project-95ed9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh4fTqXwEY0ir9FHOW1jdWf2Gg4Y3pAxk',
    appId: '1:200767412375:ios:10bfd7c87d9d2a600af1d2',
    messagingSenderId: '200767412375',
    projectId: 'smd-project-95ed9',
    storageBucket: 'smd-project-95ed9.firebasestorage.app',
    iosBundleId: 'com.example.smdProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh4fTqXwEY0ir9FHOW1jdWf2Gg4Y3pAxk',
    appId: '1:200767412375:ios:10bfd7c87d9d2a600af1d2',
    messagingSenderId: '200767412375',
    projectId: 'smd-project-95ed9',
    storageBucket: 'smd-project-95ed9.firebasestorage.app',
    iosBundleId: 'com.example.smdProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPukuTdNmQQbkQwy1w9XR4n-UA7Y6irGU',
    appId: '1:200767412375:web:5d67734eb8e313360af1d2',
    messagingSenderId: '200767412375',
    projectId: 'smd-project-95ed9',
    authDomain: 'smd-project-95ed9.firebaseapp.com',
    storageBucket: 'smd-project-95ed9.firebasestorage.app',
  );
}
